# Generated by Django 5.1 on 2024-10-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0002_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Recommend', 'Recommend'), ('Food', 'Food'), ('Appetizer', 'Appetizer'), ('Drink', 'Drink'), ('Dessert', 'Dessert')], default='Food', max_length=20),
        ),
    ]
