# Generated by Django 5.1 on 2024-10-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0003_menuitem_image_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Appetizer', 'Appetizer'), ('Drink', 'Drink'), ('Dessert', 'Dessert')], default='Food', max_length=20),
        ),
    ]
