# Generated by Django 5.1 on 2024-10-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0004_menuitem_recommend_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='special_requests',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
