# Generated by Django 5.1 on 2024-10-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0006_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
