# Generated by Django 5.1 on 2024-10-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0007_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Paying', 'Paying'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Paying', max_length=20),
        ),
    ]
