# Generated by Django 5.1 on 2024-10-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0009_remove_order_created_at_order_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
