# Generated by Django 5.1 on 2024-10-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0011_alter_payment_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=20),
        ),
    ]
